export CUDA_VISIBLE_DEVICES=0
python3 -m nrm.nrm \
    --src_embed_type=gtf_cnn_segment\
    --seg_len=5\
    --seg_embed_dim=128 \
    --num_units=256 \
    --embed_dim=512 \
    --num_gpus=2 \
    --share_vocab=False \
    --src_max_len=20 \
    --tgt_max_len=20 \
    --batch_size=256 \
    --encoder_type=bi \
    --attention=luong\
    --src=message --tgt=response \
    --vocab_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/vocab.20000.separate  \
    --train_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/train.20000\
    --dev_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/dev.20000 \
    --test_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/test.20000 \
    --out_dir=models/gate_segcnn_word_20000_level \
    --num_train_steps=1000000 \
    --steps_per_stats=100 >> logs/gate_segcnn_word_20000_level.txt
export CUDA_VISIBLE_DEVICES=0
python3 -m nrm.nrm \
    --src_embed_type=wtf_cnn_segment\
    --seg_len=5\
    --seg_embed_dim=128 \
    --num_units=256 \
    --embed_dim=512 \
    --num_gpus=2 \
    --share_vocab=False \
    --src_max_len=20 \
    --tgt_max_len=20 \
    --batch_size=256 \
    --encoder_type=bi \
    --attention=luong\
    --src=message --tgt=response \
    --vocab_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/vocab.20000.separate  \
    --train_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/train.20000\
    --dev_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/dev.20000 \
    --test_prefix=/ldev/tensorflow/nmt2/nmt/data/wordlevel/test.20000 \
    --out_dir=models/weight_segcnn_word_20000_level \
    --num_train_steps=1000000 \
    --steps_per_stats=100 >> logs/weight_segcnn_word_20000_level.txt